version: '3'
services:
  pgadmin1:
    image: 'dpage/pgadmin4'
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
    ports:
      - '80:80'
    network_mode: host
