version: '3'
services:
  postgres1:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - '5432:5432' 
  postgres2:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - '5433:5432'
  postgres3:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - '5434:5432'
